---
name: Upgrade command

on:
  pull_request:
    branches: [release-0.17]

permissions: {}

jobs:
  upgrade-command:
    name: subctl upgrade command
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        using: ['', 'globalnet,lighthouse']
    steps:
      - name: Check out the subctl repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Check out the shipyard repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          repository: submariner-io/shipyard
          path: shipyard
          ref: ${{ github.base_ref }}

      - name: Deploy old environment
        run: make deploy-latest using="${{ matrix.using }}"

      - name: Build new subctl
        run: make cmd/bin/subctl

      - name: Run upgrade command and check versions after upgrade
        run: |
          export KUBECONFIG=$(find $(git rev-parse --show-toplevel)/output/kubeconfigs/ -type f -printf %p:)
          cmd/bin/subctl upgrade
          cmd/bin/subctl version && cmd/bin/subctl show versions

      - name: Run e2e tests
        run: make e2e

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@release-0.17
