---
name: Upgrade command

on:
  pull_request:
    branches: [devel]

permissions: {}

jobs:
  upgrade-command:
    name: subctl upgrade command
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        using: ['', 'globalnet,lighthouse']
    steps:
      - name: Check out the subctl repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - name: Check out the shipyard repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          repository: submariner-io/shipyard
          path: shipyard
          ref: ${{ github.base_ref }}

      - name: Deploy old environment
        run: make deploy-latest using="${{ matrix.using }}"

      - name: Build new subctl
        run: make cmd/bin/subctl

      - name: Run upgrade command
        run: cmd/bin/subctl upgrade

      - name: Run e2e tests
        run: make e2e

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@devel
